version: '3.3'

services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass
    volumes:
      - redis-data:/var/lib/redis
    configs:
      - source: redis-config
        target: /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - internal

  etc1:
    image: etclabscore/core-geth
    command: --mordor --http --http.addr 0.0.0.0 --http.port 8545
    networks:
      - internal
    volumes:
      - etc-data:/root

  stratum:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: open-etc-pool-dev-stratum
    volumes:
      - .:/workspace:cached
    configs:
      - source: stratum-config
        target: /config.json
    container_name: open-etc-pool-dev-stratum
    command: sleep infinity
    ports:
      - 0.0.0.0:8008:8008
      - 0.0.0.0:8888:8888
      - 0.0.0.0:8080:8080
    # network_mode: service:db
    networks:
      - internal

configs:
  redis-config:
    file: ./redis.conf
  stratum-config:
    file: ./config.json

volumes:
  etc-data:
  redis-data:

networks:
  internal: